// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU99yAlVre7cbMHhKtkBCFo5rscgulPrg',
    appId: '1:1016721611740:web:4dd7ec2b3b8189054c4d19',
    messagingSenderId: '1016721611740',
    projectId: 'flutter-chato-5abf5',
    authDomain: 'flutter-chato-5abf5.firebaseapp.com',
    storageBucket: 'flutter-chato-5abf5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3emXhjvVOiA7fCrTmh_8G-XrVyQO5M-E',
    appId: '1:1016721611740:android:bf191959d0ab6b794c4d19',
    messagingSenderId: '1016721611740',
    projectId: 'flutter-chato-5abf5',
    storageBucket: 'flutter-chato-5abf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ROhcNLF7Iuz17VgQqafvp1odR3DOkJA',
    appId: '1:1016721611740:ios:a6d3df903f4bc1234c4d19',
    messagingSenderId: '1016721611740',
    projectId: 'flutter-chato-5abf5',
    storageBucket: 'flutter-chato-5abf5.appspot.com',
    iosBundleId: 'com.example.chato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ROhcNLF7Iuz17VgQqafvp1odR3DOkJA',
    appId: '1:1016721611740:ios:a6d3df903f4bc1234c4d19',
    messagingSenderId: '1016721611740',
    projectId: 'flutter-chato-5abf5',
    storageBucket: 'flutter-chato-5abf5.appspot.com',
    iosBundleId: 'com.example.chato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU99yAlVre7cbMHhKtkBCFo5rscgulPrg',
    appId: '1:1016721611740:web:d0f9b947ae27014d4c4d19',
    messagingSenderId: '1016721611740',
    projectId: 'flutter-chato-5abf5',
    authDomain: 'flutter-chato-5abf5.firebaseapp.com',
    storageBucket: 'flutter-chato-5abf5.appspot.com',
  );
}
